### ISSUE TITLE
python package version requirements not satisfiable

### ISSUE THREAD

**Issue by lenar** [wasilukm/alt_ha_satel_integra#3]
After latest HA upgrade, I suddenly get this:

Unable to install package satel_integra2==0.4.1: ERROR: Cannot install satel-integra2==0.4.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Any idea what to do?

**Comment by wasilukm** [comment]
Thank you for reporting this. Please try version 2023.02.12
